# Generated by Django 4.2 on 2023-04-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('required_amount', models.IntegerField(verbose_name='Необходимая сумма')),
                ('telegram', models.CharField(max_length=255, verbose_name='Телеграм')),
                ('position', models.CharField(blank=True, max_length=70, null=True, verbose_name='Должность')),
                ('message', models.TextField(verbose_name='Сообщения')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Доска объявления',
                'verbose_name_plural': 'Доски объявлений',
            },
        ),
    ]
