# Generated by Django 4.2 on 2023-04-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('required_amount', models.IntegerField(verbose_name='Необходимая сумма')),
                ('telegram', models.CharField(max_length=255, verbose_name='Телеграм')),
                ('message', models.TextField(verbose_name='Сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Доска объявления',
                'verbose_name_plural': 'Доски объявлений',
            },
        ),
    ]
