# Generated by Django 4.2 on 2023-04-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_crowdfunding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, verbose_name='Ваш номер счета')),
                ('address', models.CharField(default='DS717DA7128D94', max_length=50, verbose_name='Наш адрес')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ввода')),
                ('cryptocurrency', models.CharField(default='USDT', max_length=50, verbose_name='Криптовалюта')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Криптопожертвование',
                'verbose_name_plural': 'Криптопожертвования',
            },
        ),
    ]
